name: Deploy Azure Functions

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: jarvis-function
  NODE_VERSION: '20.x'
  WORKING_DIRECTORY: HttpFunctionApp    # Add this to specify the function app folder

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        cd ${{ env.WORKING_DIRECTORY }}
        npm install
        
    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ${{ env.WORKING_DIRECTORY }}